# Loading initial data into a Redis Docker container
# https://stackoverflow.com/a/33006167/2377454
version: '3.4'

services:
  cache:
    image:  redis:latest
    restart: always
    networks:
      - cache-network

  loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    links:
      - cache:cache
    depends_on:
      - cache
    networks:
      - cache-network
    command: ["python3", "loader.py", "-H", "cache", "final1.json.gz", "final2.json.gz"]

networks:
  cache-network:
